### ISSUE TITLE
indentation level 

### ISSUE THREAD

**Issue by abdhalees** [facg3/birdies#11]
There is a problem in the indentation in your code -most of it is stuck to left of the editor- this makes your code hard to read and trace.
there is a great package in atom to help you with (html&css) indentation [atom-beautify](https://atom.io/packages/atom-beautify)

**Comment by MMortaga** [comment]
Thanks Abdallah. Done installing it for me & my whole team :+1: 
![beatify](https://i.imgur.com/NchDXf7.png)
